# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 10
  timeout: 30
  reaping_frequency: 120
  port: 3306

development: &development
  <<: *default
  database: test_db
  host: localhost
  username: root
  password: Akumarvl@123

test: &test
  <<: *default
  database: edi_test
  username: root
  password:
  host: localhost
  timeout: 10000
  pool: 50

stage: &stage
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  
production: &production
  <<: *default
  database: edi_prod
  username: edi_prod
  password: p3ZCs97fx6cdswjP
  host: rds100.cbdxpogebfdz.us-west-2.rds.amazonaws.com
